import AppLayout from "../AppLayout";
import CandidatePicker from "../CandidatePicker";
import Markdown from "../Markdown";
import { ErrorPanel, LoadingPanel, PageHeader, Panel } from "../primitives";
import { useSelectedCandidate } from "@/lib/usePhaseZero";

export default function MemosPage() {
  const s = useSelectedCandidate();

  return (
    <AppLayout title="Memos" loading={s.candidatesLoading || s.detailLoading}>
      <PageHeader
        eyebrow="Diligence Library"
        title="Memos"
        subtitle="Structured diligence memos generated by the engine. A diligence input for human expert review — not a go/no-go decision."
      />

      {s.candidatesLoading && <LoadingPanel label="Loading candidates" />}
      {s.candidatesError && !s.candidatesLoading && <ErrorPanel />}

      {s.candidates && (
        <>
          <CandidatePicker
            candidates={s.candidates}
            selectedId={s.selectedId}
            onSelect={s.setSelectedId}
          />

          {s.detailLoading && <LoadingPanel label="Generating memo" />}
          {s.detailError && !s.detailLoading && <ErrorPanel />}

          {s.detail && (
            <Panel className="mt-6">
              <Markdown source={s.detail.memo} />
            </Panel>
          )}
        </>
      )}
    </AppLayout>
  );
}
