/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities/$id'

const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/memos': typeof MemosRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/simulation': typeof SimulationRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/memos': typeof MemosRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/simulation': typeof SimulationRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities': typeof OpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/memos': typeof MemosRoute
  '/models': typeof ModelsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/simulation': typeof SimulationRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/memos'
    | '/models'
    | '/research'
    | '/settings'
    | '/signals'
    | '/simulation'
    | '/opportunities/$id'
    | '/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/memos'
    | '/models'
    | '/research'
    | '/settings'
    | '/signals'
    | '/simulation'
    | '/opportunities/$id'
    | '/opportunities'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/memos'
    | '/models'
    | '/research'
    | '/settings'
    | '/signals'
    | '/simulation'
    | '/opportunities/$id'
    | '/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  MemosRoute: typeof MemosRoute
  ModelsRoute: typeof ModelsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  SimulationRoute: typeof SimulationRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  MemosRoute: MemosRoute,
  ModelsRoute: ModelsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  SimulationRoute: SimulationRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
